### ISSUE TITLE
Is OSM data used? Does this affect the licence?

### ISSUE THREAD

**Issue by amandasaurus** [delight-im/FreeGeoDB#1]
Hello. I saw your project on Hacker News today. Congratulations and good luck!

One question: In RESOURCES.md you list OpenStreetMap. Is OSM data included in this data? If so, then I think this will affect your copyright licence, since OSM is only available under the ODbL licence, and you wouldn't be able to release this under the Apache licence.

**Comment by mtmail** [comment]
@rory Came here to check the same thing. `RESOURCES.md` seem to just links to [OSM](https://www.openstreetmap.org/) and [geonames.org](http://www.geonames.org/) as alternatives. in `SOURCES.md` I see the Natural Earth dataset listed. Natural Earth is public domain, no attribution necessary.

**Comment by ocram** [comment]
@rory Thank you! We _don't_ use any OpenStreetMap data here so this does not affect the license :)

As @mtmail has pointed out correctly, the `RESOURCES.md` is not the file to look at here, it's actually the `SOURCE.md` file.

The files have now been renamed. Sorry for the confusion!

However, we should probably choose a better license: https://github.com/delight-im/FreeGeoDB/issues/9
