### ISSUE TITLE
Frontend for the application

### ISSUE THREAD

**Issue by ssubram4** [delight-im/FreeGeoDB#12]
Hi,
I am willing to contribute to open source and found your project really interesting.
Would like to create a front-end say HTML page for users to search the details.

Please let me know.
Thanks.

**Comment by ocram** [comment]
You're absolutely welcome to do this :) Thank you!

After you've built such a front-end, we could link it here in this repository in a new section called "SDKs and libraries" or something like this.

Look here for someone else who wants to build a similar thing in the form of a PHP library: https://github.com/delight-im/FreeGeoDB/issues/10
