### ISSUE TITLE
Barcelona Spain is not in "Cataluma"

### ISSUE THREAD

**Issue by adnam** [delight-im/FreeGeoDB#2]
It's in "Catalonia" (English), "Cataluña" (Spanish) or "Catalunya" (Catalan)

**Comment by ocram** [comment]
Thank you!

Tarragona and Mataro seem to have the same problem, right?

Perhaps this may also be a result of the encoding issues: https://github.com/delight-im/FreeGeoDB/issues/4

We also have to decide which language version (native or English) to use.

**Comment by ocram** [comment]
It turned out that this problem was only due to the encoding errors referenced in the other issue.

Now that those problems have been fixed, the region for "Barcelona" is correct again :)

Thank you!
