### ISSUE TITLE
Missing airports

### ISSUE THREAD

**Issue by theodorton** [delight-im/FreeGeoDB#3]
Great project :)

Did a quick search in browser after opening `airports.json` and I believe a lot of airports are missing, International airports included. A quick search for Torp/Sandefjord and Rygge returned no results, both are considered major airports in Norway with international connections.

What sources did you use for airports? There may be better sources, and if so, what do you think about how we can update the data in this repo.

**Comment by saxenanurag** [comment]
Also, the lat long data in the json is inverted. It is long lat and not lat long.

**Comment by ocram** [comment]
@theodorton Thank you!

Please see this file for the source: https://github.com/delight-im/FreeGeoDB/blob/f08c26cccf3f3f751fc5d1d0d3abae878d7b968c/Source%20and%20Build%20Instructions.md

Updating the data in this repository with your own contributions or data from other sources is absolutely appreciated :)

@saxenanurag The data is intentionally `POINT(long, lat)` which should be correct and common usage:
- https://www.drupal.org/node/511370
- http://forums.mysql.com/read.php?23,209566,210132#msg-210132
- http://blogs.msdn.com/b/isaac/archive/2007/12/27/latitude-longitude-ordering.aspx

Anyway, please let's open a separate issue for every new problem or question :)

**Comment by ocram** [comment]
@theodorton The process for making contributions has been simplified: https://github.com/delight-im/FreeGeoDB#authoritative-data-source :)
