### ISSUE TITLE
Is the license valid?

### ISSUE THREAD

**Issue by ghost** [delight-im/FreeGeoDB#5]
See https://news.ycombinator.com/item?id=10277207

**Comment by ghost** [comment]
Duplicate, sorry.

**Comment by ocram** [comment]
No problem!

Other issue was here: https://github.com/delight-im/FreeGeoDB/issues/1

And we should switch to a license that fits better than Apache 2.0: https://github.com/delight-im/FreeGeoDB/issues/9
